### ISSUE TITLE
Asking a quick question :)

### ISSUE THREAD

**Issue by physicso** [AnatoliiPotapov/MNIST-EWC#1]
I have noticed that you have chosen
$$
F_{i+1} = 0.3 \cdot F_{new} + 0.7 \cdot F_i
$$
as the update rule for the fisher elements. I was wondering why are you choosing 0.7 and 0.3 as their weights, and why not directly use
$$
F_{i+1} = F_{new}?
$$

Looking forward for your reply :)
Best

**Comment by physicso** [comment]
Oh, I think I've figured that out! By using the weights, you are introducing two or more separate penalties, right?

> This can be enforced either with two separate penalties, or as one by noting that the sum of two quadratic penalties is itself a quadratic penalty.

**Comment by AnatoliiPotapov** [comment]
O! nice to hear from you! I will definitely try more variants soon, but if I use only use penalty for last learned task then net is free to forget earlier ones. 
We can do 
$$
F_{i+1} = F_{new}?
$$
but only if we use L(of all previously learned tasks) but if so we need to store some data from all learned tasks then what is the point of doing EWC.

**Comment by AnatoliiPotapov** [comment]
I am still figuring it out so I will be glad to hear some ideas from you too :)

**Comment by physicso** [comment]
Nice to meet you too! Thank you very much for your kind reply. I think we may regard them as the hyper-parameters, kind of depending on the problem we are solving :)
